from __future__ import annotations

HIDDEN_INSTRUCTION_BODY = """\
# Harness Hidden visibility

This repository's Harness `visibility_mode` is `hidden`. Durable SCM publication is human-owned.

Do not stage, commit, amend, create or rename refs or tags, push, or create or edit pull requests, issues, reviews, or SCM comments.

Do not add agent-identifying Git or SCM text such as `Co-authored-by`, `Generated by`, `Made-with`, vendor/model signatures, agent branch prefixes, or PR/issue footers that advertise agent involvement.

Do not `git add -f` ignored files. Do not edit `.gitignore` or tracked instruction files to hide Harness artifacts. Do not delete or edit Harness-owned Hidden policy.

Ordinary source and documentation edits are allowed. Humans publish outside the agent path.
"""
