"""Connect one trusted Windows checkout to the isolated Harness MCP endpoint."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from harness.codex_adapter import codex_developer_instructions
from harness.dashboard import read_dashboard_access_token
from harness.ipc import IpcError, request_workspace_status
from harness.runtime_paths import default_runtime_paths, mcp_http_listen_port
from harness.windows_fs import require_private_windows_path, secure_owned_windows_path
from harness.workspace_resolution import WorkspaceHint, WorkspaceHintMatchMode


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, timeout=5, check=True
    )
    return result.stdout.strip()


def _config(root: Path, token: str, port: int) -> bytes:
    def quote(value: str) -> str:
        return json.dumps(value, ensure_ascii=True)

    return (
        "# Generated by scripts/dev.cmd connect-codex. Restart Codex after changes.\n"
        f"developer_instructions = {quote(codex_developer_instructions())}\n\n"
        "[mcp_servers.harness]\n"
        f"url = {quote(f'http://127.0.0.1:{port}/mcp')}\n"
        "enabled = true\nrequired = true\nstartup_timeout_sec = 30\n\n"
        "[mcp_servers.harness.http_headers]\n"
        f"Authorization = {quote('Bearer ' + token)}\n"
        f'"X-Harness-Workspace-Root" = {quote(str(root))}\n'
    ).encode()


def connect(root: Path) -> None:
    if os.name != "nt" or not os.environ.get("HARNESS_DEV_ROOT"):
        raise RuntimeError("Use scripts\\dev.cmd connect-codex on Windows")
    root = root.resolve(strict=True)
    if Path(_git(root, "rev-parse", "--show-toplevel")).resolve() != root:
        raise RuntimeError("Workspace must be a Git repository root")
    if _git(root, "ls-files", "--", ".codex/config.toml"):
        raise RuntimeError("Refusing to replace a tracked Codex configuration")

    paths = default_runtime_paths()
    try:
        request_workspace_status(
            paths.socket,
            (
                WorkspaceHint(
                    path=root, source="windows-connection", match_mode=WorkspaceHintMatchMode.ROOT
                ),
            ),
        )
    except IpcError as exc:
        raise RuntimeError(
            "Register and start this Workspace with scripts\\dev.cmd harness init <Git-root>"
        ) from exc
    token = read_dashboard_access_token(paths.database)
    if token is None:
        raise RuntimeError("Start the isolated daemon with scripts\\dev.cmd harness status first")
    port = mcp_http_listen_port(paths.socket)
    if port == 0:
        raise RuntimeError("The isolated MCP endpoint has no stable port")
    desired = _config(root, token, port)
    config = root / ".codex" / "config.toml"
    if config.exists():
        require_private_windows_path(config, directory=False)
        if config.read_bytes() != desired:
            raise RuntimeError("Existing Codex project configuration is not owned by this command")

    exclude = Path(_git(root, "rev-parse", "--git-path", "info/exclude"))
    if not exclude.is_absolute():
        exclude = root / exclude
    block = "# BEGIN HARNESS WINDOWS CODEX\n/.codex/config.toml\n# END HARNESS WINDOWS CODEX\n"
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    if block not in existing:
        if "# BEGIN HARNESS WINDOWS CODEX" in existing:
            raise RuntimeError("Git exclude contains an ambiguous Harness Windows block")
        with exclude.open("a", encoding="utf-8", newline="\n") as handle:
            if existing and not existing.endswith("\n"):
                handle.write("\n")
            handle.write(block)

    if config.exists():
        print(f"Codex project MCP configuration is current: {config}")
        return
    config.parent.mkdir(exist_ok=True)
    descriptor = os.open(config, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    try:
        secure_owned_windows_path(config, directory=False)
        with os.fdopen(descriptor, "wb") as handle:
            descriptor = -1
            handle.write(desired)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        config.unlink(missing_ok=True)
        raise
    print(f"Connected Codex to the isolated Harness daemon: {config}")
    print("Restart Codex fully and start a new conversation to load the project MCP server.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("workspace", nargs="?", type=Path, default=Path.cwd())
    args = parser.parse_args()
    try:
        connect(args.workspace)
    except (OSError, RuntimeError, subprocess.SubprocessError) as exc:
        print(f"Codex connection failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from None


if __name__ == "__main__":
    main()
